# Generated by Django 5.2.8 on 2025-11-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='installment_group',
            field=models.UUIDField(blank=True, db_index=True, help_text='Identificador do grupo de parcelas, se for uma compra parcelada.', null=True),
        ),
    ]
