# Generated by Django 5.2.8 on 2025-11-27 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_installment_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do cartão de crédito', max_length=100)),
                ('closing_day', models.PositiveSmallIntegerField(help_text='Dia do mês em que a fatura fecha (1-31)')),
                ('due_day', models.PositiveSmallIntegerField(help_text='Dia do mês em que a fatura vence (1-31)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit_card',
            field=models.ForeignKey(blank=True, help_text='Cartão de crédito utilizado (se aplicável). A data será ajustada para a data da fatura.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.creditcard'),
        ),
    ]
