# Generated by Django 5.2.8 on 2025-11-28 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_creditcard_transaction_credit_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Data de pagamento (data em que o pagamento aconteceu ou acontecerá)', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credit_card',
            field=models.ForeignKey(blank=True, help_text='Cartão de crédito utilizado (se aplicável). A payment_date será ajustada para a data de vencimento da fatura.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.creditcard'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(help_text='Data de lançamento (data em que a transação foi registrada)'),
        ),
    ]
