# Generated by Django 5.2.8 on 2025-12-02 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_change_monthlybudget_to_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybudget',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.subcategory'),
        ),
    ]
