# Generated by Django 5.2.8 on 2025-12-03 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_populate_transaction_subcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Data e hora da execução da ação')),
                ('action', models.CharField(help_text='Descrição da ação executada', max_length=255)),
                ('details', models.TextField(blank=True, help_text='Detalhes adicionais da ação (opcional)')),
                ('user', models.ForeignKey(blank=True, help_text='Usuário que executou a ação', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Ação',
                'verbose_name_plural': 'Logs de Ações',
                'ordering': ['-timestamp'],
            },
        ),
    ]
