# Generated by Django 5.2.8 on 2025-12-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_add_actionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True, help_text='Comentário opcional sobre o lançamento'),
        ),
    ]
