# Generated by Django 5.2.8 on 2025-12-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_add_comment_to_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='owner_tag',
            field=models.CharField(blank=True, choices=[('Thi', 'Thiago'), ('Tha', 'Thaís')], help_text='Tag do proprietário (obrigatório para cartão Bradesco): Thi (Thiago) ou Tha (Thaís)', max_length=3, null=True),
        ),
    ]
