# Generated by Django 5.2.8 on 2025-12-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_populate_owner_tag_bradesco'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_installment',
            field=models.BooleanField(default=True, help_text='Indica se o lançamento é parte de uma compra parcelada.'),
        ),
    ]
