# Generated by Django 5.2.8 on 2025-12-09 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_populate_is_installment_true'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_installment',
            field=models.BooleanField(default=False, help_text='Indica se o lançamento é parte de uma compra parcelada.'),
        ),
        migrations.CreateModel(
            name='BudgetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do template', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descrição opcional do template', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Usuário que criou o template (para rastreamento, mas templates são globais)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de Orçamento',
                'verbose_name_plural': 'Templates de Orçamento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor do orçamento para esta subcategoria', max_digits=14)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.subcategory')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.budgettemplate')),
            ],
            options={
                'verbose_name': 'Item do Template',
                'verbose_name_plural': 'Itens do Template',
                'unique_together': {('template', 'subcategory')},
            },
        ),
    ]
