# Generated by Django 5.2.8 on 2025-12-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_alter_transaction_is_installment_budgettemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgettemplateitem',
            name='comment',
            field=models.TextField(blank=True, help_text='Comentário opcional sobre o orçamento desta subcategoria', null=True),
        ),
        migrations.AddField(
            model_name='monthlybudget',
            name='comment',
            field=models.TextField(blank=True, help_text='Comentário opcional sobre o orçamento', null=True),
        ),
    ]
