# Generated by Django 5.2.8 on 2025-12-11 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_budgettemplateitem_comment_monthlybudget_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Descrição como aparece no cartão de crédito', max_length=200)),
                ('translation', models.CharField(help_text='Tradução/Descrição amigável', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legenda',
                'verbose_name_plural': 'Legendas',
                'ordering': ['description'],
                'unique_together': {('user', 'description')},
            },
        ),
    ]
