# Generated by Django 5.2.8 on 2025-12-13 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_add_template_items_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor do estorno', max_digits=14)),
                ('description', models.TextField(help_text='Descrição do estorno')),
                ('refund_date', models.DateField(help_text='Data do estorno')),
                ('invoice_year', models.PositiveSmallIntegerField(help_text='Ano da fatura')),
                ('invoice_month', models.PositiveSmallIntegerField(help_text='Mês da fatura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='finance.creditcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estorno de Cartão',
                'verbose_name_plural': 'Estornos de Cartão',
                'ordering': ['-refund_date', '-created_at'],
            },
        ),
    ]
