# Generated by Django 5.2.8 on 2025-12-14 16:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0024_creditcardrefund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Corretora',
                'verbose_name_plural': 'Corretoras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modalidade de Investimento',
                'verbose_name_plural': 'Modalidades de Investimento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('resgatado', 'Resgatado')], default='ativo', max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_contributed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investment.broker')),
                ('investment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investment.investmenttype')),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
                'ordering': ['broker__name', 'name'],
                'unique_together': {('broker', 'name')},
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_date', models.DateField()),
                ('is_contribution', models.BooleanField(default=True)),
                ('is_redemption', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investment.investment')),
            ],
            options={
                'verbose_name': 'Transação de Investimento',
                'verbose_name_plural': 'Transações de Investimento',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_allocated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.transaction')),
            ],
            options={
                'verbose_name': 'Investimento Pendente',
                'verbose_name_plural': 'Investimentos Pendentes',
                'ordering': ['created_at'],
            },
        ),
    ]
